route:
  route_num: 2
  route0_target_property: [1, 1, 0.0]
  route0_seg_vec: [1]
  route1_target_property: [8, 7, 0.0]
  route1_seg_vec: [2, 3, 4, 5, 6, 7, 8]


# route0_target_property = [target_node, sub_seg_num, heading]
# route0_seg_vec = [sub_seg1, sub_seg1, sub_seg1, ...]
