task_create: 6.24
goal_num: 3
ref_frame: map
delta_flag: false
goal_0: [4.0, 0.0, 90, 5]
goal_1: [3.0, 8,0, 90, 5]
goal_2: [10.0, 6.8, 90, 5]
goal_dict: {gindex_0: goal_0,gindex_1: goal_1,gindex_2: goal_2}

