task_create: 6.24
goal_num: 3
ref_frame: map
delta_flag: false
goal_0: [1.0, 0.0, 90, 5]
goal_1: [1.0, 6.0, 90, 5]
goal_2: [2.0, 2.0, 90, 5]
goal_dict: {gindex_0: goal_0,gindex_1: goal_1,gindex_2: goal_2}

