controller_frequency: 10.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:

#---4.2.1-Robot Configuration Parameters---
   acc_lim_x: 0.2
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 0.05

   max_vel_x: 1.5
   min_vel_x: 0.02
   max_vel_theta: 0.26 
   min_vel_theta: -0.26

   min_in_place_vel_theta: 0.141  # 10degree/s
   escape_vel: -0.1
   holonomic_robot: false

#---4.2.2-Goal Tolerance Parameters---
   yaw_goal_tolerance: 0.173 # about +/-10 degrees
   xy_goal_tolerance: 0.2  # 10 cm
   latch_xy_goal_tolerance: false

#---4.2.3-Forward Simulation Parameters---
   sim_time: 1.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 3
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 20
   simple_attractor: false
   controller_frequency: 10.0	# Should be same to the first line

#---4.2.4-Trajectory Scoring Parameters---
   meter_scoring: true
   pdist_scale: 0.6
   gdist_scale: 0.7
   occdist_scale: 0.7
   heading_lookahead: 0.5
   heading_scoring: true
   heading_scoring_timestep: 0.8
   dwa: true
   publish_cost_grid_pc: false

#---4.2.5-Osicillation Prevention Parameters---
   oscillation_reset_dist: 0.1

#---4.2.6-Global Plan Parameters---
   prune_plan: true
