obstacle_range: 6.0
raytrace_range: 9.0
robot_radius: 0.5
inflation_radius: 0.75
max_obstacle_height: 0.2
min_obstacle_height: 0.1
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
