controller_frequency: 5.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
   acc_lim_x: 0.2
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 0.5

   max_vel_x: 0.4
   min_vel_x: 0.05
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0

   min_in_place_vel_theta: 0.5
   escape_vel: -0.1
   holonomic_robot: false

   yaw_goal_tolerance: 0.1 # about 6 degrees
   xy_goal_tolerance: 0.1  # 10 cm
   latch_xy_goal_tolerance: false

   sim_time: 1.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 5
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 20
   simple_attractor: false

   meter_scoring: true
   pdist_scale: 0.5
   gdist_scale: 0.7
   occdist_scale: 0.7
   heading_lookahead: 0.5
   heading_scoring: true
   heading_scoring_timestep: 0.8
   dwa: true
   publish_cost_grid_pc: false

   oscillation_reset_dist: 0.1

   prune_plan: true
